# Generated by Django 4.2.21 on 2025-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
