# Generated by Django 4.2.21 on 2025-06-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_internship_requirement_internship_responsibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="category",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="skill",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="internship",
            name="requirement",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="internship",
            name="responsibility",
            field=models.JSONField(default=list, null=True),
        ),
    ]
