# Generated by Django 4.2.21 on 2025-06-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0006_internship_category_internship_skill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="season",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
