# Generated by Django 4.2.21 on 2025-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0007_internship_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="date_posted",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
