# Generated by Django 4.2.21 on 2025-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0008_internship_date_posted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internship",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="internship",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
