# Generated by Django 4.2.21 on 2025-06-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0009_alter_internship_options_internship_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
