# Generated by Django 4.2.23 on 2025-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0011_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="likes",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="likes",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
