# Generated by Django 4.2.23 on 2025-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0013_remove_likes_likes_count_blog_likes_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("date_posted", models.CharField(max_length=255, null=True)),
                ("season", models.CharField(max_length=255, null=True)),
                ("requirement", models.JSONField(default=list, null=True)),
                ("responsibility", models.JSONField(default=list, null=True)),
                ("category", models.JSONField(default=list, null=True)),
                ("skill", models.JSONField(default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
